Strict fail no defs
iambumblehead/esmock pull request #193
Opened 2023-03-15 05:56 UTC by Swivelgames

Updated esmockModule to throw if there are no mocks or global mocks at strictest.

Fixes #192

2023-03-17 15:38 UTC, koshic requested changes

2023-03-17 15:38 UTC, koshic commented on tests/tests-node/esmock.node.test.js
> +    '../local/strictest.js', {}
I propose to use importsCoreLocalAndPackage.js instead of my simple demo - strictest.js

2023-03-17 17:39 UTC, iambumblehead commented
This MR looks good to me, thank you @koshic and @Swivelgames. It would be nice if we could merge a solution to the jest/node19 issue before this mr.

Would one of you submit a different MR one set of changes: update jest and jest-light-runner to latest versions in test folders? Maybe that alone will resolve the failing tests. If it doesn't work and if something more involved is needed, maybe I can look into it on Saturday

------
_unrelated_

A month or so back, I did a little experiment and found esmock can be updated to mock global functions, for example to mock node's native "fetch". I've been busy and haven't wrapped up those changes or pushed them up here.

2023-03-18 20:06 UTC, iambumblehead commented
still occupied and busy with another thing, maybe I can update next weekend

2023-03-18 20:16 UTC, koshic commented
> still occupied and busy with another thing, maybe I can update next weekend
I'll try to get some time this weekend and fix it too. Now I working on 'less verbose' wrapper to integrate esmock with node native tests, without that real tests require too long boilerplate.

2023-03-23 21:32 UTC, koshic commented
@iambumblehead jest updated

2023-03-23 21:52 UTC, koshic approved these changes

2023-03-23 22:15 UTC, iambumblehead commented
@koshic thanks looks good

2023-03-23 22:16 UTC, iambumblehead approved these changes

2023-03-23 22:41 UTC, merged

2023-03-23 23:47 UTC, iambumblehead commented
thanks @Swivelgames